services:
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - macrix-app
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: macrix
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always   
volumes:
  pgdata:
networks:
  macrix-app:    